import os
import sys
import types

# MetaTrader5 is a Windows-only binary package, so app modules that import it can't
# be imported on Linux CI. Inject a stub exposing just the constants the code under
# test references, before any app import. setdefault keeps a real install if present.
_mt5 = types.ModuleType("MetaTrader5")
_mt5.ORDER_TIME_GTC = 0
_mt5.ORDER_TIME_DAY = 1
_mt5.ORDER_TIME_SPECIFIED = 2
_mt5.ORDER_TIME_SPECIFIED_DAY = 3
_constant_names = """
COPY_TICKS_ALL ORDER_FILLING_FOK ORDER_FILLING_IOC ORDER_FILLING_RETURN
ORDER_TYPE_BUY ORDER_TYPE_BUY_LIMIT ORDER_TYPE_BUY_STOP ORDER_TYPE_BUY_STOP_LIMIT
ORDER_TYPE_SELL ORDER_TYPE_SELL_LIMIT ORDER_TYPE_SELL_STOP ORDER_TYPE_SELL_STOP_LIMIT
TIMEFRAME_D1 TIMEFRAME_H1 TIMEFRAME_H4 TIMEFRAME_M1 TIMEFRAME_M15 TIMEFRAME_M30
TIMEFRAME_M5 TIMEFRAME_MN1 TIMEFRAME_W1 TRADE_ACTION_DEAL TRADE_ACTION_MODIFY
TRADE_ACTION_PENDING TRADE_ACTION_REMOVE TRADE_ACTION_SLTP TRADE_RETCODE_CANCEL
TRADE_RETCODE_CLIENT_DISABLES_AT TRADE_RETCODE_CLOSE_ONLY
TRADE_RETCODE_CLOSE_ORDER_EXIST TRADE_RETCODE_CONNECTION TRADE_RETCODE_DONE
TRADE_RETCODE_DONE_PARTIAL TRADE_RETCODE_ERROR TRADE_RETCODE_FIFO_CLOSE
TRADE_RETCODE_FROZEN TRADE_RETCODE_INVALID TRADE_RETCODE_INVALID_CLOSE_VOLUME
TRADE_RETCODE_INVALID_EXPIRATION TRADE_RETCODE_INVALID_FILL
TRADE_RETCODE_INVALID_ORDER TRADE_RETCODE_INVALID_PRICE TRADE_RETCODE_INVALID_STOPS
TRADE_RETCODE_INVALID_VOLUME TRADE_RETCODE_LIMIT_ORDERS
TRADE_RETCODE_LIMIT_POSITIONS TRADE_RETCODE_LIMIT_VOLUME TRADE_RETCODE_LOCKED
TRADE_RETCODE_LONG_ONLY TRADE_RETCODE_MARKET_CLOSED TRADE_RETCODE_NO_CHANGES
TRADE_RETCODE_NO_MONEY TRADE_RETCODE_ONLY_REAL TRADE_RETCODE_ORDER_CHANGED
TRADE_RETCODE_PLACED TRADE_RETCODE_POSITION_CLOSED TRADE_RETCODE_PRICE_CHANGED
TRADE_RETCODE_PRICE_OFF TRADE_RETCODE_REJECT TRADE_RETCODE_REJECT_CANCEL
TRADE_RETCODE_REQUOTE TRADE_RETCODE_SERVER_DISABLES_AT TRADE_RETCODE_SHORT_ONLY
TRADE_RETCODE_TIMEOUT TRADE_RETCODE_TOO_MANY_REQUESTS TRADE_RETCODE_TRADE_DISABLED
""".split()
for _index, _name in enumerate(_constant_names, start=10):
    setattr(_mt5, _name, _index)

# Values whose semantics are asserted directly by application code.
_mt5.ORDER_TYPE_BUY = 0
_mt5.ORDER_TYPE_SELL = 1
_mt5.TRADE_RETCODE_PLACED = 10008
_mt5.TRADE_RETCODE_DONE = 10009
_mt5.TRADE_RETCODE_DONE_PARTIAL = 10010
_mt5.TRADE_RETCODE_TIMEOUT = 10012
_mt5.DEAL_ENTRY_IN = 0
_mt5.DEAL_ENTRY_OUT = 1
_mt5.DEAL_ENTRY_INOUT = 2
_mt5.DEAL_ENTRY_OUT_BY = 3
sys.modules.setdefault("MetaTrader5", _mt5)

# Keep route tests independent of the optional documentation UI dependency.
_flasgger = types.ModuleType("flasgger")
_flasgger.swag_from = lambda *args, **kwargs: lambda function: function
sys.modules.setdefault("flasgger", _flasgger)

# App modules import their siblings by bare name (e.g. `from order_time import ...`),
# so the app dir must be on the path.
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "app"))
